name: Run Hello Script

on:
  schedule:
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  run-hello:
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run hello.js
        env:
          READ_TIMEOUT_SECRETS: ${{ secrets.READ_TIMEOUT_SECRETS || 'default_value' }}
          READ_TIMEOUT_VARIABLE: ${{ secrets.READ_TIMEOUT_VARIABLE || 'default_value' }}
        run: node hello.js
